version: '2'

# Data-sink services
# ====================
#
# - CNTR: container

services:
  connect:
    image: debezium/connect-jdbc-es:0.9
    build:
      context: 
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - postgres
    environment:
     - GROUP_ID=connect-sink
     - BOOTSTRAP_SERVERS=${KAFKA_SERVER}:29094
     - CONFIG_STORAGE_TOPIC=connect-sink_configs
     - OFFSET_STORAGE_TOPIC=connect-sink_offsets
     - STATUS_STORAGE_TOPIC=connect-sink_statuses
     - KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
     - VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
     - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://${KAFKA_SERVER}:8081
     - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://${KAFKA_SERVER}:8081
#     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
#     - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
#     - LOG_LEVEL=DEBUG
