version: '2'

# Kafka service
# ====================
#
# - CNTR: container

services:
  zookeeper:
    build:
      context: ./img-build/zookeeper
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
  kafka-server:
    build:
      context: ./img-build/kafka
    volumes:
      - ./kafka-data:/kafka/data
      - ./kafka-logs:/kafka/logs
      - ./kafka-config:/kafka/config
    ports:
      - 19092:9092
      - 39094:29094
    links:
      - zookeeper
    environment:
      BROKER_ID: 1
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'CNTR'
      KAFKA_DELETE_TOPIC_ENABLE: 'TRUE'
      ADVERTISED_LISTENERS: >-
        CNTR://kafka-server:29092,
        CLOUD://${CLOUD_HOST}:9092
      LISTENERS: >-
        CNTR://:29092,
        CLOUD://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        CNTR:PLAINTEXT,
        CLOUD:PLAINTEXT
