version: '2'

# Data-source services
# ====================
#
# - CNTR: container

services:
  connect:
    image: krealo/connect-alpine-zulu:0.6
    # build:
    #   context: ./img-build/connect
    ports:
      - 8083:8083
      - 5005:5005
    volumes:
      - ./.secrets:/secrets
    environment:
      GROUP_ID: 'connect-source'
      BOOTSTRAP_SERVERS: 'kafka-server:9092'
      CONFIG_STORAGE_TOPIC: 'connect-source_configs'
      OFFSET_STORAGE_TOPIC: 'connect-source_offsets'
      STATUS_STORAGE_TOPIC: 'connect-source_statuses'
      KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: >-
        http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: >-
        http://schema-registry:8081
      CONNECT_MAX_REQUEST_SIZE: 2097152
      CONNECT_CONFIG_PROVIDERS: file
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: >-
        org.apache.kafka.common.config.provider.FileConfigProvider
    extra_hosts:
      - "kafka-server:${KAFKA_SERVER}"
      - "schema-registry:${SCHEMA_REGISTRY_SERVER}"
      - "postgres:${PG_SERVER}"
